### PR TITLE
fails when gets "real" workflow

### PR DESCRIPTION
**Pull request by seregasheypak**
Seems like connection with shared lib is not properly configured...

### CODE REVIEW

**Comment by sakserv** [comment]
Hey @seregasheypak - sorry for the delay here. It seems the test still fails. I spent a bit of time debugging and was able to resolve the Share Lib issues. However, I'm encountering a new issue once the "real" workflow starts and haven't quite had the time to get that one resolved. I'll update this PR once I've committed the working version.

**Comment by sakserv** [comment]
Hey @seregasheypak - I went ahead and committed the fixes to the Share Lib setup. The "real" workflow still fails, but I'm getting closer to a resolution.

The "real" workflow was missing the input and output directories for the MR job, adding those allows the MR job to get submitted, however, Oozie is unable to retrieve the status of the job and ultimately fails, despite the MR job succeeding. This seems to be ATS/JHS related, but I haven't been able to resolve this failure yet. I'll continue to work on that as time permits.

If you have time to take a look, that would be much appreciated as well. As HDP 2.6 released this week, I'm going to be a bit tied up with that integration. 

Thanks!

**Comment by seregasheypak** [comment]
@sakserv I'm on black side (CDH). My guess that oozie cluster doesn't properly configure / mock presence / absence of shared lib (according to log output). I'm compiling your stuff with CDH and I get exactly the same result in CDH world.

**Comment by sakserv** [comment]
@seregasheypak thanks for the continued patience. :)

I pushed some changes to the oozie test. I've commented out the Oozie client status polling so the test passes. 

Note that the shared lib issues are resolved. I've also updated the MR jobs with the necessary input/output settings so they run.

At this point, the workflow can be submitted and the MR jobs successfully run. The remaining issue is that Oozie client is unable to poll the status of the MR jobs. This appears to be AHS related. I see the following log entry repeated until the number of attempts is exhausted.

```2017-04-22 12:02:02 INFO  MapReduceActionExecutor:520 - USER[skumpf] GROUP[users] TOKEN[] APP[sugar-option-decision] JOB[0000000-170422120112054-oozie-skum-W] ACTION[0000000-170422120112054-oozie-skum-W@first] Trying to get job [job_local1119689956_0001], attempt [7]```

I'm continuing to look into this. Please feel free to poke at the latest update as well.

**Comment by sakserv** [comment]
Hey @seregasheypak - I've been able to get much further on tracking down the issue here, or should I say four issues here. :)

My fix to the sharelib was incorrect and the fact that oozie was expecting the sharelib to be on the local filesystem was a giveaway to the issue.

Here is what I've found so far:
1. The MR job needs the input and output set.
2. The configuration being set in OozieLocalCluster was not saved/serialized out to the oozie hadoop-conf directory. This was the big one, default configs were being written out. As a result, oozie and MR were running in local mode.
3. The sharelib was not actually being populated. The plumbing was there, but it was not being called.
4. The MR cluster was not using fixed ports for the Job History Server, so the status of the job could not be obtained by oozie.

I need to do some clean up of previous patches, and I'm now running into an issue with bash on my workstation (error=7 argument list too long), but I hope to have a fixed version up yet this weekend.

**Comment by sakserv** [comment]
The issue I was having with too many arguments is due to the low limits on OSX and large classpath with all of the shared lib jars on it. I've added a Shared Lib Frameworks feature to only load the shared lib libraries that are needed for the type of Oozie job being run. This speeds up run times quite a bit versus loading the full shared lib. See the integration test for how to use it.

I'm about to push the final update here with the "real" workflow working. I will close this out once it gets through CI.

Thanks again for your patience. Please let me know if you still have trouble. You can open a new ticket or reopen one of the existing ones.

**Comment by sakserv** [comment]
The fix has been committed. Thanks!

**Pull request closed without merging**
