### PR TITLE
Bump HDP version to 2.6.3.0

### PR DESCRIPTION
**Pull request by explicite**
For components versions I based on http://public-repo-1.hortonworks.com/HDP/centos7/2.x/updates/2.6.3.0/build_metadata.txt

Only com.github.sakserv.minicluster.impl.LocalGatewayConfig requires changes. 

@sakserv I cannot find any contribution dock.

### CODE REVIEW

**Comment by jpawio** [comment]
@sakserv looks like tests pass. Can you release it some how? We need this to fix our it tests. If you are not able to do that fast then we will start develop our fork.

Cheers,
Explicite

**Comment by explicite** [comment]
@sakserv looks like PR is ok. Can you please release fast this change? 

Cheers,
JP

**Comment by explicite** [comment]
@Fokko can you please merge and make release?

**Comment by explicite** [comment]
I can't wait to much time for release. You can merge changes from https://github.com/explicite/hadoop-mini-clusters/tree/feature/hdp_2.6.3.0

**Comment by Fokko** [comment]
@explicite I don't have commit rights on the repo

**Comment by sakserv** [comment]
Sorry folks, free time has been difficult to come by lately, but I should have more time going forward to get these merged in a reasonable time frame.

I've just pushed support for HDP 2.6.3.0 and fixed a couple other lingering issues in the process. I'll cut a release shortly once CI wraps up.

**Comment by sakserv** [comment]
0.1.15 has been released, which includes support for HDP 2.6.3.0. It may take a bit of time for it to show up in maven central.

**Comment by Fokko** [comment]
Thanks @sakserv

**Comment by explicite** [comment]
Nice, thanks @sakserv. Cannot send any PW so I will ask here. Do you have some TODO list with features/bugfixes? I want to create some Scala API for this project.

**Pull request closed without merging**
