### PR TITLE
Add Knox

### PR DESCRIPTION
**Pull request by Treydone**

### CODE REVIEW

**Comment by sakserv** [comment]
@Treydone - thank you very much for the high quality contribution! I'm not exactly sure why travis is failing, but I'm looking into it now. 

I'll get this merged soon and will make it part of the 0.1.10 release. I'm hoping to hear back on the couple of open issues before I cut that release, as I'd like to include any fixes that may come about there. If I don't hear anything in a couple days, I'll go ahead and release.

**Comment by sakserv** [comment]
@Treydone - I just commented on the patch. I released 0.1.9 just yesterday, sorry about that. If you can update the pom to 0.1.10-SNAPSHOT, I think that will fix the issue. Thanks!

**Comment by Treydone** [comment]
Ok, seems to be good now!

**Comment by sakserv** [comment]
LGTM, thanks again!

**Comment by sakserv** [comment]
These changes have been included in 0.1.10 which was just released. Thanks again!

**Pull request merged**
